"""Presentation strings sent by Python to the production web shell."""

WEB_TEXT = {
    "vi": {
        "app_title": "Dịch ảnh hàng loạt",
        "dashboard": "Bảng điều khiển",
        "configuration": "Cấu hình",
        "actions": "Thao tác",
        "process_log": "Nhật ký xử lý",
        "service": "Dịch vụ",
        "batch_size": "Số ảnh mỗi lần",
        "start_from": "Bắt đầu từ ảnh",
        "source_folder": "Thư mục ảnh gốc",
        "output_folder": "Thư mục lưu ảnh VN",
        "profile": "Profile trình duyệt",
        "account": "Tài khoản ChatGPT",
        "account_fallback": "Tự chuyển tài khoản khi hết lượt",
        "auto_next": "Tự chạy batch tiếp theo",
        "auto_next_delay": "Chờ (phút)",
        "main": "Chạy batch mới",
        "retry": "Chạy lại ảnh lỗi",
        "force": "Chạy lại ảnh này",
        "continue": "Tiếp tục sau can thiệp",
        "stop": "Dừng",
        "save": "Lưu cấu hình",
        "browse": "Chọn",
        "open_output": "Mở kết quả",
        "copy_log": "Copy log",
        "export_log": "Xuất log",
        "clear_log": "Xóa log",
        "run_now": "Chạy ngay",
        "cancel_auto": "Hủy tự chạy",
        "theme": "Giao diện",
        "language": "Ngôn ngữ",
        "ready": "Sẵn sàng",
        "manual_banner": "Đang chờ bạn can thiệp trong trình duyệt.",
        "accounts": "Tài khoản",
        "account_name": "Tên gợi nhớ",
        "add": "Thêm",
        "rename": "Đổi tên",
        "remove": "Bỏ khỏi danh sách",
        "login": "Đăng nhập",
        "saved": "Đã lưu cấu hình.",
        "progress": "Tiến trình",
        "status_running": "Đang chạy...",
        "process_done": "Đã dừng / hoàn tất",
        "manual_wait": "Đang chờ bạn can thiệp trong trình duyệt...",
        "continue_sent": "Đã gửi lệnh tiếp tục...",
        "stopped": "Đã dừng",
        "no_process": "Không có tiến trình đang chạy",
        "auto_cancelled": "Đã hủy tự chạy batch tiếp theo.",
        "auto_countdown": "Batch tiếp theo sau {time}",
        "auto_next_recovered": "=== Worker thoát mã {code} sau khi đã báo batch thành công; vẫn tự chạy tiếp an toàn. ===",
        "auto_skip_failed": "=== Không tự chạy: batch vừa xong có ảnh lỗi hoặc thiếu ảnh thành công. ===",
        "auto_skip_incomplete": "=== Không tự chạy: batch vừa xong chưa đủ {count} ảnh. ===",
        "auto_skip_intervened": "=== Không tự chạy: đã có can thiệp thủ công trong lần chạy này. ===",
        "auto_skip_process_error": "=== Không tự chạy: worker kết thúc với mã {code}. ===",
        "auto_skip_no_more": "=== Không tự chạy: không còn ảnh đủ điều kiện để chạy tiếp. ===",
        "auto_skip_missing_result": "=== Không tự chạy: không nhận được kết quả batch đầy đủ từ worker. ===",
        "batch_result_log": "=== Kết quả batch: {success}/{selected} thành công, {failed} lỗi. ===",
        "account_quota_log": "⚠ {name} đã hết lượt tạo ảnh. Đang tìm tài khoản tiếp theo...",
        "account_switched_log": "🔁 Đã chuyển sang {name}; đang chạy lại ảnh {image}.",
        "account_skipped_log": "↷ Bỏ qua {name}: {reason}.",
        "account_waiting_log": "⏸ Tạm dừng: {reason}. Ảnh đang dở: {image}.",
        "account_waiting_status": "Đang chờ tài khoản ChatGPT khả dụng...",
        "login_ready": "Phiên ChatGPT đã sẵn sàng.",
        "complete_outcome": "Job hoàn tất: {done}/{total} ảnh.",
        "waiting_quota_outcome": "Batch tạm dừng: {reason}. Ảnh đang dở: {image}.",
        "needs_retry_outcome": "Job đã dừng: còn {failed} ảnh cần chạy lại.",
        "invalid_auto_next_delay": "Thời gian chờ tự chạy phải là số dương.",
        "error_detail": "Lỗi: {error}",
        "event_gap": "Thiếu sự kiện giao diện: chờ {expected}, nhận {actual}.",
        "error": "Lỗi",
    },
    "en": {
        "app_title": "Batch Image Translator",
        "dashboard": "Dashboard",
        "configuration": "Configuration",
        "actions": "Actions",
        "process_log": "Process log",
        "service": "Service",
        "batch_size": "Images per batch",
        "start_from": "Start from image",
        "source_folder": "Source image folder",
        "output_folder": "VN output folder",
        "profile": "Browser profile",
        "account": "ChatGPT account",
        "account_fallback": "Switch accounts when quota is exhausted",
        "auto_next": "Automatically run next batch",
        "auto_next_delay": "Wait (minutes)",
        "main": "Run new batch",
        "retry": "Retry failed images",
        "force": "Rerun this image",
        "continue": "Continue after manual step",
        "stop": "Stop",
        "save": "Save settings",
        "browse": "Browse",
        "open_output": "Open output",
        "copy_log": "Copy log",
        "export_log": "Export log",
        "clear_log": "Clear log",
        "run_now": "Run now",
        "cancel_auto": "Cancel auto-run",
        "theme": "Theme",
        "language": "Language",
        "ready": "Ready",
        "manual_banner": "Waiting for your manual action in the browser.",
        "accounts": "Accounts",
        "account_name": "Account name",
        "add": "Add",
        "rename": "Rename",
        "remove": "Remove",
        "login": "Sign in",
        "saved": "Settings saved.",
        "progress": "Progress",
        "status_running": "Running...",
        "process_done": "Stopped / completed",
        "manual_wait": "Waiting for your manual action in the browser...",
        "continue_sent": "Continue command sent...",
        "stopped": "Stopped",
        "no_process": "No process is running",
        "auto_cancelled": "Automatic next batch cancelled.",
        "auto_countdown": "Next batch in {time}",
        "auto_next_recovered": "=== The worker exited with code {code} after reporting full success; continuing safely. ===",
        "auto_skip_failed": "=== Not auto-running: the completed batch has failed or incomplete images. ===",
        "auto_skip_incomplete": "=== Not auto-running: the completed batch has fewer than {count} images. ===",
        "auto_skip_intervened": "=== Not auto-running: this run had manual intervention. ===",
        "auto_skip_process_error": "=== Not auto-running: the worker exited with code {code}. ===",
        "auto_skip_no_more": "=== Not auto-running: no eligible images remain. ===",
        "auto_skip_missing_result": "=== Not auto-running: the worker did not return a complete batch result. ===",
        "batch_result_log": "=== Batch result: {success}/{selected} succeeded, {failed} failed. ===",
        "account_quota_log": "⚠ {name} exhausted its image quota. Looking for the next account...",
        "account_switched_log": "🔁 Switched to {name}; retrying image {image}.",
        "account_skipped_log": "↷ Skipping {name}: {reason}.",
        "account_waiting_log": "⏸ Paused: {reason}. Unfinished image: {image}.",
        "account_waiting_status": "Waiting for an available ChatGPT account...",
        "login_ready": "The ChatGPT session is ready.",
        "complete_outcome": "Job complete: {done}/{total} images.",
        "waiting_quota_outcome": "Batch paused: {reason}. Unfinished image: {image}.",
        "needs_retry_outcome": "Job stopped: {failed} images still need retrying.",
        "invalid_auto_next_delay": "The automatic-run delay must be a positive number.",
        "error_detail": "Error: {error}",
        "event_gap": "UI event gap: expected {expected}, received {actual}.",
        "error": "Error",
    },
}
